"use client";

import { useState, useEffect } from "react";
import BrandCard from "../../components/BrandCard";
import { supabase } from "../../lib/supabaseClient";

export default function Trending(){
 const[user,setUser]=useState(null),[posts,setPosts]=useState([]),[loading,setLoading]=useState(true);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>setUser(data.user));},[]);
 useEffect(()=>{async function load(){const[{data:postData,error:postError},{data:voteData,error:voteError}]=await Promise.all([supabase.from("posts").select("*").order("created_at",{ascending:false}),supabase.from("votes").select("post_id,value")]);if(postError||voteError)console.error("Trending load error",{postError,voteError});const upvotes=new Map();(voteData||[]).forEach(v=>{if(Number(v.value)===1)upvotes.set(v.post_id,(upvotes.get(v.post_id)||0)+1);});setPosts((postData||[]).map(p=>({id:p.id,name:p.brand_name,category:p.category,note:p.post_type==="thread"?p.body:p.note,location:"",color:"#8A7F6B",image:p.image_url,mediaUrls:Array.isArray(p.media_urls)&&p.media_urls.length?p.media_urls:(p.image_url?[p.image_url]:[]),postType:p.post_type,isReal:true,upvotes:upvotes.get(p.id)||0,createdAt:p.created_at})).sort((a,b)=>b.upvotes-a.upvotes||new Date(b.createdAt)-new Date(a.createdAt)));setLoading(false);}load();},[]);
 return <main className="page"><div className="topbar container"><a href="/" className="wordmark">thredori</a><h1>Trending</h1></div><p className="note container">The finds getting the most love from the Thredori community.</p>{loading?<p className="status container">Loading...</p>:posts.length===0?<p className="status container">Nothing posted yet.</p>:<section className="grid container">{posts.map(post=><BrandCard key={post.id} brand={post} user={user}/>)}</section>}<style jsx>{` .page{min-height:100vh;background:var(--cotton)}.topbar{display:flex;align-items:center;gap:16px;padding:16px 20px;border-bottom:1px solid var(--cotton-line)}.wordmark{font-family:var(--font-voice);font-style:italic;font-size:19px;color:var(--ink)}h1{font-family:var(--font-voice);font-size:18px;margin:0}.note{padding:14px 20px 0;font-size:12px;color:var(--muted)}.status{padding:30px 20px;color:var(--muted);font-size:13px}.grid{display:grid;grid-template-columns:1fr;gap:14px;padding:10px 20px 40px;align-items:start}.grid :global(.brand-card){min-width:0;margin:0}.grid :global(.polaroid){overflow:hidden}.grid :global(.brand-photo){width:100%;height:260px;object-fit:cover;display:block}@media(min-width:640px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(min-width:960px){.grid{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(min-width:1400px){.grid{grid-template-columns:repeat(5,minmax(0,1fr))}} `}</style></main>;
}
